name: Detekt Static Analysis

on:
  pull_request:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  pull-requests: write

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Detekt
        run: ./gradlew detekt --stacktrace

      - name: Setup reviewdog
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Report Detekt findings with reviewdog
        if: github.event_name == 'pull_request'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          REPORTS=$(find . -type f -path "*/build/reports/detekt/detekt.xml" || true)
          if [ -z "$REPORTS" ]; then
            echo "No detekt.xml reports found."
            exit 0
          fi
          for report in $REPORTS; do
            echo "Reporting $report"
            reviewdog -f=checkstyle -name="detekt ($report)" -reporter=github-pr-review -level=warning -fail-on-error=false < "$report"
          done